config/routes.rb
Rails.application.routes.draw do
  get 'instructors/:id/courses', to: "instructors#courses", as: "instructor_courses_path"
  get 'profiles/:user_id/courses', to: "profiles#courses", as: "user_courses"
  get 'instructors/:id/new_course', to: "instructors#new_course", as: "new_instructor_course"

  resources :instructors

  resources :courses do
    resources :reviews
  end

  resources :users do
    resource :profile
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/home'
  root 'welcome#home'

  get '/instructors/:id/next', to: 'instructors#next_instructor'

  get '/instructors/:id/previous', to: 'instructors#previous_instructor'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]

  def index
    @courses = Course.all.order(created_at: :desc).page(params[:page])

    respond_to do |f|
      f.html {render :index}
      f.json {render json: @courses, status: 200}
    end
  end

  def show
    @course = Course.find(params[:id])
    #binding.pry
    @reviews = @course.reviews
    #@review = @course.reviews.build
    # @reviews = @course.reviews.reverse
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @course, status: 200}
    end
    #render json: @course, status: 200
  end

  # def new
  #   @course = Course.new
  #   @course.build_intructor()
  # end

  #def create
  #  @course = Course.new(course_params)
  #  binding.pry
  #  if @course.save
  #    redirect_to course_path(@course)
  #  else
  #    flash.now[:alert] = "You must enter a name and description of the course"
  #    render "new"
  #  end
  #end

  def edit
    @course = Course.find_by(id: params[:id])
    @course.build_instructor() unless @course.instructor
  end

  def update
    @course = Course.find_by(id: params[:id])
    @course.update(course_params)
    if @course.save
      redirect_to course_path(@course)
    else
      render "edit"
    end
  end

  def destroy
    @course = Course.find_by(id: params[:id])
    @course.destroy
    redirect_to root_path
  end

  def new_review
    @review = @course.reviews.build(review_params) #in video build create method in review controller and might need to add review_params in here
    if @review.save
      render 'reviews/show', :layout => false
    else
      render "courses/show"
    end
  end

  private

  def course_params
    params.require(:course).permit(:id,
      :user_id,
      :title,
      :description,
      :department,
      :course_number,
      instructor_attributes: [
        :id,
        :user_id,
        :first_name,
        :second_name
      ]
    )
  end

  def authorize
    unless current_user.try(:admin?) || current_user.id == Course.find_by(id: params[:id]).user_id
      flash[:error] = "You are not authorized to view this page."
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course_details_for_index.html.erb
<ol>
  <% @courses.each do |course| %>
    <li><h3><%= course.full_title%></h3>
      <h5><%= course.instructor_name %></h5>
  <p class="card-text"><%= truncate course.description, length: 50 %></p>
      <div class="card-body">
        <% if course.overall_quality == "No reviews" %>
          No reviews
        <% else %>
          <% course.overall_quality.floor.times do %>
          <% end %>
          <% if course.overall_quality - course.overall_quality.floor > 0.25 && course.overall_quality - course.overall_quality.floor < 0.75 %>
          <% elsif course.overall_quality - course.overall_quality.floor > 0.75 %>
          <% end %>
          <% (5 - course.overall_quality).floor.times do %>
          <% end %>
        <% end %>
      </div>
        <div class="btn-group">
          <%= button_to "View", course_path(course), method: :get, class: "btn btn-sm btn-outline-secondary" unless params[:action] == 'show' && params[:controller] == 'courses' %>
          <%= button_to "Edit", edit_course_path(course), method: :get, class: "btn btn-sm btn-outline-secondary" if current_user.try(:admin?) || course.user_id == current_user.try(:id) %>
        </div>
        <br>
        <small class="text-muted">Last updated: <%= course.updated_at.strftime("%m/%d/%Y") %></small>
  <% end %></li>
  </ol>

app/views/courses/_form.html.erb
<% if course.errors.any? %>
      <div id="error_explanation">
          <h2><%= pluralize(course.errors.count, "error") %> prohibited this activity from being saved:</h2>
          <ul>
              <% course.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
          </ul>
      </div>
  <% end %>
  <%= form_for course do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
      <br>
      <%= f.label :Department %><br>
      <%= f.text_field :department, placeholder: "4 letter abbreviation" %>
      <br>
      <%= f.label :course_number %><br>
      <%= f.text_field :course_number, placeholder: "must be 3 numbers" %>
      <br>
      <%= f.label :Description %><br>
      <%= f.text_area :description %>
      <br>
      <fieldset>
        <legend>Instructor</legend>
        <%= f.fields_for :instructors do |instructor| %>
        <%= instructor.hidden_field :user_id, value: current_user.id %>

        <%= content_tag(:strong, "Either select an instructor or add a new one (below):") %>

        <%= instructor.collection_check_boxes(:instructor_ids, Instructor.all, :id, :second_name) do |b| %>
          <br><%= b.label(class: "label-checkbox") { b.check_box + b.object.second_name}%>
        <% end %>
        <br><br>
          <%= instructor.label :first_name %><br>
          <%= instructor.text_field :first_name %>
          <br>
          <%= instructor.label :second_name, "Last Name" %><br>
          <%= instructor.text_field :second_name %>
        <% end %>
      </fieldset>
    <br>
    <%= f.submit %>
<% end %>
<br>
<%= button_to "Delete Course", course, :method => :delete, class: "btn btn-outline-danger" if !!course.id && (current_user.try(:admin?) || current_user.id == course.user_id) %>

app/views/courses/edit.html.erb
<h3>Edit Course</h3>
  <%= render partial: "form", locals: { course: @course} %>

app/views/courses/index.html.erb
<div class="course-header">
  <div class="container">
    <h1 class="course-title">Courses</h1>
  </div>
</div>

<%= link_to "Load Courses", courses_path(@courses), :class => "load_courses" %>

  <div class="blog-post">
      <%= page_entries_info @courses %>
      <%= paginate @courses, window: 2 %>
      <div class="courses">
        <ol id=indexCourses>
        </ol>
      </div>
  </div>

app/views/courses/new.html.erb
<h3>Create a new course</h3>
<%= link_to "Or add an instructor", new_instructor_path %>
<br>
<br>
  <%= render partial: "form", locals: { course: @course} %>

app/views/courses/show.html.erb
<div id="showcourse">
  <div class="course-header">
    <h1><%= @course.title %> (<%= @course.department %>-<%= @course.course_number %>)</h1>
  </div>
</div>
<h3>Instructor: <%= @course.instructor_name%></h3>

<p id="description"><%= @course.description %></p>
    <%= link_to "Edit course", edit_course_path(@course) if current_user.try(:admin?) || @course.user_id == current_user.try(:id) %><br>
    <%= link_to "All courses", courses_path, class: "btn btn-outline-dark" %>

<h3>Reviews</h3>

<p>Overall Ratings</p>
  <ul>
    <li> Average Difficulty: <%= @course.avg_difficulty %></li>
    <li> Instructor Quality: <%= @course.instructor_quality %></li>
    <li> Workload: <%= @course.work_amount %></li>
    <li> Amount Learned: <%= @course.amount_learned %></li>
    <li> Overall Quality: <%= @course.overall_quality %></li>
  </ul>

<br>

<!-- <%= link_to "Write a review", new_course_review_path(@course), :class => "new_review", :remote => true %> | -->
<h3>Options:</h3>
  <ul>
    <li><%= link_to "Go to Reviews Index page", course_reviews_path(@course)%></li>
    <li><%= link_to "Load Reviews", course_reviews_path(@course), :class => "load_reviews" %></li>
  </ul>

<div>
  <ol id="test">
  </ol>
</div>


<%= form_for([@course, @course.reviews.build], data: { disable_with: false }) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :course_id, value: @course.id %>
  <label>How difficult was this course? (Enter 1 - 5)</label>
  <%= f.text_field :difficulty %><br>
  <label>What was the quality of this course's instructor (Professor <%= @course.instructor_name%>)? (Enter 1 - 5)</label>
  <%= f.text_field :instructor_quality %><br>
  <label>How much did you learn from this course? (Enter 1 - 5)</label>
  <%= f.text_field :amount_learned %><br>
  <label>How much work did this course require? (Enter 1 - 5)</label>
  <%= f.text_field :work_amount %><br>
  <label>What was the overall quality of this course? (Enter 1 - 5)</label>
  <%= f.text_field :course_quality %><br>

  <label>Comments</label><br>
  <%= f.text_area :comment %><br>
      <%= f.submit %>
      <%= link_to "Back to course", course_path(@course) %>
  <% end %>