config/routes.rb
Rails.application.routes.draw do
  get 'instructors/:id/courses', to: "instructors#courses", as: "instructor_courses_path"
  get 'profiles/:user_id/courses', to: "profiles#courses", as: "user_courses"
  get 'instructors/:id/new_course', to: "instructors#new_course", as: "new_instructor_course"

  resources :instructors

  resources :courses do
    resources :reviews
  end

  resources :users do
    resource :profile
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/home'
  root 'welcome#home'

  get '/instructors/:id/next', to: 'instructors#next_instructor'

  get '/instructors/:id/previous', to: 'instructors#previous_instructor'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:index, :show]
  before_action :authorize, only: [:edit, :update, :destroy]
  before_action :set_course

  def index
    @course = Course.find(params[:course_id])
    @reviews = @course.reviews

  	# render :json => @reviews
    respond_to do |format|
      format.json { render json: @reviews, status:200 }
      format.html {render :index}
    end
  end

  def show
    @course = @course = Course.find(params[:course_id])
    @review = @course.reviews.find_by(id: params[:id])
  end

  def new
    @course = Course.find(params[:course_id])
    @review = Review.new
  end

  def create
   @review = @course.reviews.build(review_params)
   # render json: @review, status: 201
   if @review.save
     respond_to do |format|
       format.html { redirect_to @course }
       format.json { render json: @review, status: 201 }
     end
   else
     render 'courses/show'
   end
  end

  def edit
    @course = Course.find_by(id: params[:course_id])
    @review = Review.find_by(id: params[:id])
  end

  def update
    @course = Course.find_by(id: params[:course_id])
    @review = Review.find_by(id: params[:id])
    @review.update(review_params)
    if @review.save
      redirect_to @review.course
    else
      render "edit"
    end
  end

  def destroy
    @course = Course.find_by(id: params[:course_id])
    @review = Review.find_by(id: params[:id])
    @review.destroy
    redirect_to @course
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end


  def review_params
    params.require(:review).permit(:difficulty, :course_quality, :instructor_quality, :amount_learned, :work_amount, :comment, :user_id, :course_id, :instructor_id)
  end

  def authorized?
    if current_user != Review.find_by(params[:id]).user
      flash[:error] = "You may only edit reviews that you created"
      redirect_back(fallback_location: root_path)
    end
  end

  def authorize
    unless current_user.try(:admin?) || current_user.id == Review.find_by(id: params[:id]).user_id
      flash[:error] = "You are not authorized to edit this content."
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def last_updated(review)
    review.updated_at.strftime("Last updated %A, %b %e, at %l:%M %p")
  end
end

app/views/reviews/_form.html.erb
<% if review.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>
            <ul>
                <% review.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
<h2>Review of <%= @course.title %></h2>
<%= form_for([ :course, review]) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :course_id, value: @course.id %>
  <label>How difficult was this course? (Enter 1 - 5)</label>
  <%= f.text_field :difficulty %><br>
  <label>What was the quality of this course's instructor (Professor <%= @course.instructor_name%>)? (Enter 1 - 5)</label>
  <%= f.text_field :instructor_quality %><br>
  <label>How much did you learn from this course? (Enter 1 - 5)</label>
  <%= f.text_field :amount_learned %><br>
  <label>How much work did this course require? (Enter 1 - 5)</label>
  <%= f.text_field :work_amount %><br>
  <label>What was the overall quality of this course? (Enter 1 - 5)</label>
  <%= f.text_field :course_quality %><br>

  <label>Comments</label><br>
  <%= f.text_area :comment %><br>
      <%= f.submit %>
      <%= link_to "Back to course", course_path(@course) %>
<% end %>

app/views/reviews/_reviews.html.erb
<ol>
  <% @reviews.each do |review| %>
    <li><%= review.course_quality%></li>
  <% end %>
</ol>

app/views/reviews/create.js.erb
$("#reviews-section").append("<%= j 'reviews/review' ");
$('#review_comment_<%= @course.id %>').val('')

app/views/reviews/edit.html.erb
<%= render partial: "form", locals: { review: @review, course: @course} %>

app/views/reviews/index.html.erb
<h2>Reviews for <%= @course.full_title %> </h2>

<ol>
  <% @reviews.each do |review| %>
    <li><%= link_to "Show review", course_review_path(@course, review), :class => "review_link", :id => review.id%></li>

  <% end %>
</ol>

app/views/reviews/new.html.erb
<%= render partial: "form", locals: { review: @review, course: @courses} %>

app/views/reviews/show.html.erb
<h2=class></h2>
  <div class="review-box card rounded">
    <h4 class="ratings">Ratings</h4>
      <p>Course Difficulty: <%=@review.difficulty%> | Instructor Quality: <%=@review.instructor_quality%> | Amount Learned: <%=@review.amount_learned%></li> | Workload: <%=@review.work_amount%></li> | Course Quality: <%=@review.course_quality%></p>
    <h4>Comment</h4>
      <p><%= @review.comment %></p>
    <p><%= link_to @review.user.email, user_profile_path(@review.user) %> | <%= last_updated @review %></p>
  </div>
  <% if current_user == @review.user %>
    <%= link_to "Edit your review", edit_course_review_path(id: @review.id, course_id: @course.id) %>
     |
    <%= link_to "Delete your review", course_review_path(@course, @review), :method => :delete %>
  <% end %>
  <br><br>
  <%= link_to "Back to Course", course_path(@course) %>
  <br>
  <%= link_to "List of Course Reviews", course_reviews_path(@course) %>
  <br><br>